=== luca-zanchetta/Tesina-NewInfostud/Xml/commenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="commenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="commento" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="commento"> <!-- singola "riga" della tabella -->
    <xsd:complexType>
        <xsd:sequence>
        <xsd:element ref="id" minOccurs="1" maxOccurs="1" /> <!-- forse Ã¨ un attributo? -->
        <xsd:element ref="corpo"  minOccurs="1" maxOccurs="1" />
        <xsd:element ref="matricolaStudente" minOccurs="1" maxOccurs="1" />
        <xsd:element ref="accordoMedio" minOccurs="1" maxOccurs="1" />
        <xsd:element ref="idPost" minOccurs="1" maxOccurs="1" />
        <xsd:element ref="data" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>   
    </xsd:complexType>
    </xsd:element>
    <xsd:element name="id" type="xsd:integer"/>
    <xsd:element name="corpo" type="xsd:string"/>
    <xsd:element name="matricolaStudente" type="xsd:integer"/>
    <xsd:element name="accordoMedio" type="xsd:float"/>
    <xsd:element name="idPost" type="xsd:integer"/>
    <xsd:element name="data" type="xsd:string"/>
</xsd:schema>

=== luca-zanchetta/Tesina-NewInfostud/Xml/commenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<commenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="commenti.xsd">
<commento><id>1</id><corpo>Te li posso inviare io!</corpo><matricolaStudente>3</matricolaStudente><accordoMedio>4.00</accordoMedio><idPost>1</idPost><data>2022-08-26</data></commento></commenti>
