=== luca-zanchetta/Tesina-NewInfostud/Xml/docenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="docenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="docente" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="docente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="matricola" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="cognome" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="password" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="stato" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="matricola" type="xsd:integer"/>
    <xsd:element name="nome" type="xsd:string"/>
    <xsd:element name="cognome" type="xsd:string"/>
    <xsd:element name="password" type="xsd:string"/>
    <xsd:element name="stato" type="xsd:integer"/>
</xsd:schema>

=== luca-zanchetta/Tesina-NewInfostud/Xml/docenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<docenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="docenti.xsd">
  <docente>
    <matricola>1</matricola>
    <nome>Umberto</nome>
    <cognome>Nanni</cognome>
    <password>meglio che niente</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>2</matricola>
    <nome>Marco</nome>
    <cognome>Temperini</cognome>
    <password>marte</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>3</matricola>
    <nome>Massimo</nome>
    <cognome>Petrarca</cognome>
    <password>corporigido</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>4</matricola>
    <nome>Paolo</nome>
    <cognome>Di Lorenzo</cognome>
    <password>segnali</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>5</matricola>
    <nome>Alberto</nome>
    <cognome>Bersani</cognome>
    <password>congiuntivo</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>6</matricola>
    <nome>Bruno</nome>
    <cognome>Cifra</cognome>
    <password>rettesghembe</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>7</matricola>
    <nome>Giuseppe</nome>
    <cognome>Scotti</cognome>
    <password>peppe75</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>8</matricola>
    <nome>Paolo</nome>
    <cognome>Di Giamberardino</cognome>
    <password>salute</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>9</matricola>
    <nome>Gianluca</nome>
    <cognome>Cima</cognome>
    <password>paint</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>10</matricola>
    <nome>Fulvio</nome>
    <cognome>Schettino</cognome>
    <password>economiediscala</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>11</matricola>
    <nome>Marco</nome>
    <cognome>Toppi</cognome>
    <password>campo</password>
    <stato>1</stato>
  </docente>
  <docente>
    <matricola>12</matricola>
    <nome>Roberto</nome>
    <cognome>Beraldi</cognome>
    <password>you86</password>
    <stato>1</stato>
  </docente>
</docenti>
