=== luca-zanchetta/Tesina-NewInfostud/Xml/faqs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="faqs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="faq" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="faq">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="id" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="domanda" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="risposta" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="utilitaTotale" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="idCorso" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="idAutore" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="stato" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="id" type="xsd:integer"/>
    <xsd:element name="domanda" type="xsd:string"/>
    <xsd:element name="risposta" type="xsd:string"/>
    <xsd:element name="utilitaTotale" type="xsd:string"/>
    <xsd:element name="idCorso" type="xsd:integer"/>
    <xsd:element name="idAutore" type="xsd:integer"/>
    <xsd:element name="stato" type="xsd:integer"/>
</xsd:schema>

=== luca-zanchetta/Tesina-NewInfostud/Xml/faqs.xml
<?xml version="1.0" encoding="UTF-8"?>
<faqs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="faqs.xsd">
    <faq>
        <id>1</id>
        <domanda>Prova pietro</domanda>
        <risposta>dio dsadasdsadasdas </risposta>
        <utilitaTotale>0</utilitaTotale>
        <idCorso>1</idCorso>
        <idAutore>-1</idAutore>
    </faq>
    <faq>
        <id>2</id>
        <domanda>Yo bto</domanda>
        <risposta />
        <utilitaTotale>0</utilitaTotale>
        <idCorso>1</idCorso>
        <idAutore>1</idAutore>
    </faq>
    <faq>
        <id>3</id>
        <domanda>YO MAN&#13;
</domanda>
        <risposta>duce duce duce</risposta>
        <utilitaTotale>0</utilitaTotale>
        <idCorso>1</idCorso>
        <idAutore>0</idAutore>
    </faq>
    <faq>
        <id>4</id>
        <domanda>Ã¨ reato essere un bastardo negro?&#13;
</domanda>
        <risposta>SI</risposta>
        <utilitaTotale>0</utilitaTotale>
        <idCorso>1</idCorso>
        <idAutore>0</idAutore>
    </faq>
</faqs>
