=== luca-zanchetta/Tesina-NewInfostud/Xml/prenotazione.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="prenotazioni">  <!-- Tabella delle prenotazioni agli appelli -->
   <xsd:complexType> 
      <xsd:sequence>
	      <xsd:element ref="prenotazione" minOccurs="1" maxOccurs="1" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="prenotazione">  <!-- Singola prenotazione -->
   <xsd:complexType> 
      <xsd:sequence>
        <xsd:element ref="id" minOccurs="1" maxOccurs="1" /> 
        <xsd:element ref="matricolaStudente" minOccurs="1" maxOccurs="1" />
        <xsd:element ref="idAppello" minOccurs="1" maxOccurs="1" /> 
        <xsd:element ref="esito" minOccurs="1" maxOccurs="1" /> 
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="id" type="xsd:short" />
<xsd:element name="matricolaStudente" type="xsd:integer" />
<xsd:element name="idAppello" type="xsd:short" />
<xsd:element name="esito" type="xsd:string" />

</xsd:schema>

=== luca-zanchetta/Tesina-NewInfostud/Xml/prenotazione.xml
<?xml version="1.0" encoding="UTF-8"?>
<prenotazioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="prenotazione.xsd">
  <prenotazione>
    <id>1</id>
    <matricolaStudente>1</matricolaStudente>
    <idAppello>3</idAppello>
    <esito>24</esito>
  </prenotazione>
  <prenotazione>
    <id>2</id>
    <matricolaStudente>1</matricolaStudente>
    <idAppello>5</idAppello>
    <esito>29</esito>
  </prenotazione>
<prenotazione><id>3</id><matricolaStudente>1</matricolaStudente><idAppello>7</idAppello><esito>B</esito></prenotazione></prenotazioni>
