=== luca-zanchetta/Tesina-NewInfostud/Xml/votoCommento.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="votiCommento">  <!-- Tabella dei voti sui commenti -->
   <xsd:complexType> 
      <xsd:sequence>
	      <xsd:element ref="votoCommento" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="votoCommento">  <!-- Singolo voto -->
   <xsd:complexType> 
      <xsd:sequence>
        <xsd:element ref="id" minOccurs="1" maxOccurs="1" /> 
        <xsd:element ref="matricolaStudente" minOccurs="1" maxOccurs="1" />
        <xsd:element ref="idCommento" minOccurs="1" maxOccurs="1" /> 
        <xsd:element ref="accordo" minOccurs="1" maxOccurs="1" /> 
	     <xsd:element ref="idAutoreCommento" minOccurs="1" maxOccurs="1" /> 
        <xsd:element ref="stato" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="id" type="xsd:short" />
<xsd:element name="matricolaStudente" type="xsd:integer" />
<xsd:element name="idCommento" type="xsd:short" />
<xsd:element name="accordo" type="xsd:short" />
<xsd:element name="idAutoreCommento" type="xsd:integer" /> 
<xsd:element name="stato" type="xsd:integer"/>
</xsd:schema>

=== luca-zanchetta/Tesina-NewInfostud/Xml/votoCommento.xml
<?xml version="1.0" encoding="UTF-8"?>
<votiCommento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="votoCommento.xsd">

<votoCommento><id>1</id><matricolaStudente>3</matricolaStudente><idCommento>1</idCommento><accordo>4</accordo><idAutoreCommento>4</idAutoreCommento><stato>0</stato></votoCommento><votoCommento><id>2</id><matricolaStudente>3</matricolaStudente><idCommento>1</idCommento><accordo>3</accordo><idAutoreCommento>4</idAutoreCommento><stato>0</stato></votoCommento><votoCommento><id>3</id><matricolaStudente>3</matricolaStudente><idCommento>1</idCommento><accordo>4</accordo><idAutoreCommento>4</idAutoreCommento><stato>1</stato></votoCommento><votoCommento><id>4</id><matricolaStudente>5</matricolaStudente><idCommento>1</idCommento><accordo>4</accordo><idAutoreCommento>4</idAutoreCommento><stato>1</stato></votoCommento><votoCommento><id>5</id><matricolaStudente>4</matricolaStudente><idCommento>4</idCommento><accordo>3</accordo><idAutoreCommento>5</idAutoreCommento><stato>1</stato></votoCommento><votoCommento><id>6</id><matricolaStudente>11</matricolaStudente><idCommento>1</idCommento><accordo>4</accordo><idAutoreCommento>4</idAutoreCommento><stato>1</stato></votoCommento><votoCommento><id>7</id><matricolaStudente>11</matricolaStudente><idCommento>8</idCommento><accordo>4</accordo><idAutoreCommento>4</idAutoreCommento><stato>1</stato></votoCommento><votoCommento><id>8</id><matricolaStudente>3</matricolaStudente><idCommento>10</idCommento><accordo>4</accordo><idAutoreCommento>12</idAutoreCommento><stato>1</stato></votoCommento></votiCommento>
