=== luca-zanchetta/Tesina-NewInfostud/XSD/studenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="studenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="studente" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="studente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="matricola" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="cognome" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="password" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="dataNascita" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="reputazioneTotale" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="cfuTotale" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="media" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="idCorsoDiLaurea" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="matricola" type="xsd:integer"/>
    <xsd:element name="nome" type="xsd:string"/>
    <xsd:element name="cognome" type="xsd:string"/>
    <xsd:element name="password" type="xsd:string"/>
    <xsd:element name="dataNascita" type="xsd:string"/>
    <xsd:element name="reputazioneTotale" type="xsd:integer"/>
    <xsd:element name="cfuTotale" type="xsd:integer"/>
    <xsd:element name="media" type="xsd:float"/>
    <xsd:element name="idCorsoDiLaurea" type="xsd:integer"/>
</xsd:schema>

=== luca-zanchetta/Tesina-NewInfostud/Xml/studenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<studenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="studenti.xsd">
    <studente>
        <matricola>1</matricola>
        <nome>Mario</nome>
        <cognome>Rossi</cognome>
        <password>supermario</password>
        <dataNascita>2000-07-07</dataNascita>
        <reputazioneTotale>0</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>2</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>2</matricola>
        <nome>Luca</nome>
        <cognome>Zanchetta</cognome>
        <password>nero</password>
        <dataNascita>1997-02-28</dataNascita>
        <reputazioneTotale>0</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>3</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>3</matricola>
        <nome>Mattia</nome>
        <cognome>Aquilina</cognome>
        <password>viola</password>
        <dataNascita>2000-09-05</dataNascita>
        <reputazioneTotale>10</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>1</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>4</matricola>
        <nome>Giovanni</nome>
        <cognome>Tagliaferri</cognome>
        <password>norma</password>
        <dataNascita>2000-08-18</dataNascita>
        <reputazioneTotale>8.67</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>1</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>5</matricola>
        <nome>Alessandro</nome>
        <cognome>Brighenti</cognome>
        <password>neworld</password>
        <dataNascita>2000-06-12</dataNascita>
        <reputazioneTotale>0</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>1</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>6</matricola>
        <nome>Sara</nome>
        <cognome>Mazzanti</cognome>
        <password>Taurus</password>
        <dataNascita>1997-02-23</dataNascita>
        <reputazioneTotale>0</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>2</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>7</matricola>
        <nome>Lorena</nome>
        <cognome>Padovano</cognome>
        <password>verde</password>
        <dataNascita>2000-11-17</dataNascita>
        <reputazioneTotale>0</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>3</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>8</matricola>
        <nome>Sandra</nome>
        <cognome>Studiosi</cognome>
        <password>arancione</password>
        <dataNascita>1997-02-03</dataNascita>
        <reputazioneTotale>0</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>2</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
    <studente>
        <matricola>9</matricola>
        <nome>Remo</nome>
        <cognome>Dellucci</cognome>
        <password>marrone</password>
        <dataNascita>1997-12-19</dataNascita>
        <reputazioneTotale>0</reputazioneTotale>
        <cfuTotale>0</cfuTotale>
        <media>0</media>
        <idCorsoDiLaurea>3</idCorsoDiLaurea>
        <stato>1</stato>
    </studente>
</studenti>
